# Site settings
title: GlassLimipid -Looking for a glass cup for yourself
description: '-A glass for you.' # this means to ignore neGwlines until "baseurl:"
permalink: ':title:output_ext'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://glasslimpid.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/assets/img/branding/glasslogo.png"
logo-icon: "/assets/img/favicon/favicon.ico"
logo-icon-SEO: "/assets/img/favicon/favicon.ico" # must be a non SVG file

# Night/Dark mode
# Default mode is "auto", "auto" is for auto nightshift
# (19:00 - 07:00), "manual" is for manual toggle, and
# "on/off" is for default on/off.
#
# Whatever the user's choice is, it will supersede the
# default setting of the site and be kept during the
# visit (session). Only the dark mode setting is "manual",
# it will be always kept on every visit (i.e. no matter
# the browser is closed or not)
night_mode: "off"

logo-dark: "/assets/img/branding/MVM-logo-full-dark.svg"
highlight_theme: syntax-base16.monokai.dark # select a dark theme for the code highlighter if needed

# Author settings
author: GlassLimpid office # add your name
author-pic: mylogosquar.png
<<<<<<< HEAD
company:
  profile: "GlassLimpid Office was established in 2010, and for over a decade, we have been dedicated to producing high-quality glassware, especially glass cups. Our company has grown from a small workshop to a well-known enterprise with modern production equipment and a professional design team. We always adhere to the principle of balancing innovation and quality to meet the ever-changing market demands."
  history_and_goals: "Since its inception, GlassLimpid Office has upheld the philosophy of 'quality first, customer foremost,' leading to steady growth. Our products have gained a good reputation in the domestic market and successfully entered the international market, earning the love and trust of consumers worldwide. In the future, we will continue to focus on technological innovation and product development, striving to become a leader in the global glassware industry."
  minimalist_spirit: "GlassLimpid Office pursues minimalism in product design. We believe that simple designs not only enhance the beauty of the product but also better showcase the purity and transparency of glass. Each glass cup is meticulously designed, with every line and shape reflecting the essence of minimalist art. Through our products, we aim to allow users to experience the purity and simplicity of life."
  craftsmanship: "At GlassLimpid Office, every glass cup embodies the spirit of craftsmanship. We have a team of experienced artisans who pour immense passion and effort into every production step. From blowing and cutting to polishing and final quality inspection, every process is strictly controlled to achieve perfection. This meticulous approach ensures that each of our products boasts superior quality and unique character."
  conclusion: "GlassLimpid Office will continue to uphold the spirit of minimalism and craftsmanship, providing consumers with more high-quality glassware. We believe that with our dedication and passion, we will achieve even greater success in the future and create a beautiful future together with you."
=======
about-author: At OceanBreeze Glassware, our journey is one of passion, precision, and perseverance. For decades, we have been dedicated to the art of glassmaking, blending traditional craftsmanship with modern aesthetics to create pieces that are both timeless and exquisite.Our commitment to craftsmanship is unwavering. Every OceanBreeze Glass Tumbler is a testament to the skill and dedication of our artisans, who pour their heart and soul into each creation. With meticulous attention to detail, they shape and refine every glass, ensuring that it meets our exacting standards of quality and beauty.We believe in the power of minimalist design. Inspired by the serene beauty of nature, our glassware embodies simplicity and elegance. The textured patterns and tranquil hues of our tumblers are carefully chosen to evoke a sense of calm and sophistication, enhancing the drinking experience with every sip.Our history is rich and storied, rooted in a tradition of excellence that spans generations. We have honed our techniques over the years, constantly innovating while staying true to our core values. This legacy of craftsmanship and design excellence is reflected in every piece we create, making OceanBreeze Glassware a symbol of enduring beauty and quality.We are deeply grateful for your trust and support. By choosing OceanBreeze, you become a part of our story—a story of dedication, artistry, and a relentless pursuit of perfection. Thank you for allowing us to bring a touch of our heritage into your home.Warm regards.
>>>>>>> 8d40df73d5d7731acfc696c7ef06c968fb78932f

# Contact links
email: GlassLimipid@163.com # Add your Email address
phone: # Add your Phone number
website:  # Add your website
linkedin:  # Add your Linkedin handle
github:  # Add your Github handle
twitter:  # Add your Twitter handle
bandcamp:  # Add your Bandcamp username
stackoverflow:  # Add your stackoverflow account

# Newsletter
mailchimp: "https://github.us1.list-manage.com/subscribe/post?u=8ece198b3eb260e6838461a60&amp;id=397d90b5f4"

# Tracker
analytics: G-R8SZS2YBZK
fbadmin: ar.maybach

# Paginate
paginate: 6
paginate_path: 'page:num'
words_per_minute: 200

extensions:
  mermaid_enable: true

# Comments
comments: utteranc  #[disqus, utteranc]
comments_opts:
  comments_curtain: yes # leave empty to show the disqus embed directly
  repo: # The GitHub repo URL.  https://utteranc.es/
  issue_term: # The GitHub issue label
  label: # The GitHub comments label
  theme: # The GitHub comment's there. e.g. github-dark
  # Disqus
  discus_identifier: # Add your discus identifier

# Build settings
markdown: kramdown
mathjax: true
highlighter: rouge
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

# Outputting
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

category_archive:
  type: liquid
  path: /categories/

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]

collections:
  corporatecultures:
    output: true  
    
  jionuss:
    output: true
